apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-limits
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-memory-limit
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - argocd
                - monitoring
                - ingress-nginx
                - local-path-storage
      validate:
        message: "Memory limit is required for every container."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
